### ISSUE TITLE
All dates are timezone aware !

### ISSUE THREAD

**Issue by gmaze** [argovis/argovis_api#265]
Hi folks,
I noticed that all dates returned from "https://argovis-api.colorado.edu/argo" are timezone aware datetimes.

For instance data from "https://argovis-api.colorado.edu/argo?id=6902916_123" will return:
```python
data[0]['date_updated_argovis'] = '2023-02-01T04:03:59.529Z'
data[0]['source'] = [{'source': ['argo_core'],
  'url': 'ftp://ftp.ifremer.fr/ifremer/argo/dac/coriolis/6902916/profiles/D6902916_123.nc',
  'date_updated': '2023-01-13T15:52:26.000Z'}]
```

I don't know how to work with this, because I don't know the time zone of the server where data are processed. Therefore, I cannot get the appropriate date of Argo observations !

I can understand why the "date_updated_argovis" is timezone aware, but not the "date_updated" from the source file, this one should/must be UTC

thanks for checking this out or for explaining what I'm missing here

**Comment by katieannemills** [comment]
Hi @gmaze - thanks for reporting here; all dates reported in Argovis are UTC and reported per ISO 8601; the 'Z' is for 'Zulu', or UTC. Considering your example, compare https://argovis-api.colorado.edu/argo?id=6902916_123 to profile 123 in https://fleetmonitoring.euro-argo.eu/float/6902916; we report the exact same time.

Does this make sense? Please let me know if I'm missing your question.

**Comment by gmaze** [comment]
Hi @BillMills 
2 things lead me the wrong way:
- Numpy was sending a warning about the timezone aware string but I missed the point that the 'Z' was for UTC.
- I looked at the 'date_updated' value and is was a couple of hours shifted compared to the fleet monitoring info. I understand now that the observation time is in the 'timestamp' field
Thanks for your quick reply !
